//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knx.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Knx.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Enum_AlarmReaction_AlarmPositionDown {
            get {
                return ResourceManager.GetString("Enum.AlarmReaction.AlarmPositionDown", resourceCulture);
            }
        }
        
        public static string Enum_AlarmReaction_AlarmPositionUp {
            get {
                return ResourceManager.GetString("Enum.AlarmReaction.AlarmPositionUp", resourceCulture);
            }
        }
        
        public static string Enum_AlarmReaction_NoAlarmIsUsed {
            get {
                return ResourceManager.GetString("Enum.AlarmReaction.NoAlarmIsUsed", resourceCulture);
            }
        }
        
        public static string Enum_AlarmReaction_Reserved {
            get {
                return ResourceManager.GetString("Enum.AlarmReaction.Reserved", resourceCulture);
            }
        }
        
        public static string Enum_OnOffAction_Off {
            get {
                return ResourceManager.GetString("Enum.OnOffAction.Off", resourceCulture);
            }
        }
        
        public static string Enum_OnOffAction_OffOn {
            get {
                return ResourceManager.GetString("Enum.OnOffAction.OffOn", resourceCulture);
            }
        }
        
        public static string Enum_OnOffAction_On {
            get {
                return ResourceManager.GetString("Enum.OnOffAction.On", resourceCulture);
            }
        }
        
        public static string Enum_OnOffAction_OnOff {
            get {
                return ResourceManager.GetString("Enum.OnOffAction.OnOff", resourceCulture);
            }
        }
        
        public static string Enum_UpDownAction_Down {
            get {
                return ResourceManager.GetString("Enum.UpDownAction.Down", resourceCulture);
            }
        }
        
        public static string Enum_UpDownAction_DownUp {
            get {
                return ResourceManager.GetString("Enum.UpDownAction.DownUp", resourceCulture);
            }
        }
        
        public static string Enum_UpDownAction_Up {
            get {
                return ResourceManager.GetString("Enum.UpDownAction.Up", resourceCulture);
            }
        }
        
        public static string Enum_UpDownAction_UpDown {
            get {
                return ResourceManager.GetString("Enum.UpDownAction.UpDown", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Unit_Acknowledge {
            get {
                return ResourceManager.GetString("Unit.Acknowledge", resourceCulture);
            }
        }
        
        public static string Unit_ActiveInactive {
            get {
                return ResourceManager.GetString("Unit.ActiveInactive", resourceCulture);
            }
        }
        
        public static string Unit_AlarmNoAlarm {
            get {
                return ResourceManager.GetString("Unit.AlarmNoAlarm", resourceCulture);
            }
        }
        
        public static string Unit_AndOr {
            get {
                return ResourceManager.GetString("Unit.AndOr", resourceCulture);
            }
        }
        
        public static string Unit_Angle {
            get {
                return ResourceManager.GetString("Unit.Angle", resourceCulture);
            }
        }
        
        public static string Unit_BlindsMode {
            get {
                return ResourceManager.GetString("Unit.BlindsMode", resourceCulture);
            }
        }
        
        public static string Unit_CalculatedFixed {
            get {
                return ResourceManager.GetString("Unit.CalculatedFixed", resourceCulture);
            }
        }
        
        public static string Unit_CyclicallyOrStartStop {
            get {
                return ResourceManager.GetString("Unit.CyclicallyOrStartStop", resourceCulture);
            }
        }
        
        public static string Unit_EnableDisable {
            get {
                return ResourceManager.GetString("Unit.EnableDisable", resourceCulture);
            }
        }
        
        public static string Unit_HighLow {
            get {
                return ResourceManager.GetString("Unit.HighLow", resourceCulture);
            }
        }
        
        public static string Unit_Hours {
            get {
                return ResourceManager.GetString("Unit.Hours", resourceCulture);
            }
        }
        
        public static string Unit_IncreaseDecrease {
            get {
                return ResourceManager.GetString("Unit.IncreaseDecrease", resourceCulture);
            }
        }
        
        public static string Unit_InvertedNotInverted {
            get {
                return ResourceManager.GetString("Unit.InvertedNotInverted", resourceCulture);
            }
        }
        
        public static string Unit_KelvinPerPercent {
            get {
                return ResourceManager.GetString("Unit.KelvinPerPercent", resourceCulture);
            }
        }
        
        public static string Unit_Lux {
            get {
                return ResourceManager.GetString("Unit.Lux", resourceCulture);
            }
        }
        
        public static string Unit_mA {
            get {
                return ResourceManager.GetString("Unit.mA", resourceCulture);
            }
        }
        
        public static string Unit_Milliseconds {
            get {
                return ResourceManager.GetString("Unit.Milliseconds", resourceCulture);
            }
        }
        
        public static string Unit_Minutes {
            get {
                return ResourceManager.GetString("Unit.Minutes", resourceCulture);
            }
        }
        
        public static string Unit_None {
            get {
                return ResourceManager.GetString("Unit.None", resourceCulture);
            }
        }
        
        public static string Unit_Occupancy {
            get {
                return ResourceManager.GetString("Unit.Occupancy", resourceCulture);
            }
        }
        
        public static string Unit_OnOff {
            get {
                return ResourceManager.GetString("Unit.OnOff", resourceCulture);
            }
        }
        
        public static string Unit_OpenClose {
            get {
                return ResourceManager.GetString("Unit.OpenClose", resourceCulture);
            }
        }
        
        public static string Unit_Pa {
            get {
                return ResourceManager.GetString("Unit.Pa", resourceCulture);
            }
        }
        
        public static string Unit_Percentage {
            get {
                return ResourceManager.GetString("Unit.Percentage", resourceCulture);
            }
        }
        
        public static string Unit_Power {
            get {
                return ResourceManager.GetString("Unit.Power", resourceCulture);
            }
        }
        
        public static string Unit_PowerDensity {
            get {
                return ResourceManager.GetString("Unit.PowerDensity", resourceCulture);
            }
        }
        
        public static string Unit_Ppm {
            get {
                return ResourceManager.GetString("Unit.Ppm", resourceCulture);
            }
        }
        
        public static string Unit_Pulses {
            get {
                return ResourceManager.GetString("Unit.Pulses", resourceCulture);
            }
        }
        
        public static string Unit_RainAmount {
            get {
                return ResourceManager.GetString("Unit.RainAmount", resourceCulture);
            }
        }
        
        public static string Unit_RampNoRamp {
            get {
                return ResourceManager.GetString("Unit.RampNoRamp", resourceCulture);
            }
        }
        
        public static string Unit_Reset {
            get {
                return ResourceManager.GetString("Unit.Reset", resourceCulture);
            }
        }
        
        public static string Unit_SceneAB {
            get {
                return ResourceManager.GetString("Unit.SceneAB", resourceCulture);
            }
        }
        
        public static string Unit_Seconds {
            get {
                return ResourceManager.GetString("Unit.Seconds", resourceCulture);
            }
        }
        
        public static string Unit_StartStop {
            get {
                return ResourceManager.GetString("Unit.StartStop", resourceCulture);
            }
        }
        
        public static string Unit_Temperature {
            get {
                return ResourceManager.GetString("Unit.Temperature", resourceCulture);
            }
        }
        
        public static string Unit_TemperatureDifference {
            get {
                return ResourceManager.GetString("Unit.TemperatureDifference", resourceCulture);
            }
        }
        
        public static string Unit_TemperatureF {
            get {
                return ResourceManager.GetString("Unit.TemperatureF", resourceCulture);
            }
        }
        
        public static string Unit_TemperatureGradient {
            get {
                return ResourceManager.GetString("Unit.TemperatureGradient", resourceCulture);
            }
        }
        
        public static string Unit_TimeDifferenceMS {
            get {
                return ResourceManager.GetString("Unit.TimeDifferenceMS", resourceCulture);
            }
        }
        
        public static string Unit_TimeDifferenceS {
            get {
                return ResourceManager.GetString("Unit.TimeDifferenceS", resourceCulture);
            }
        }
        
        public static string Unit_Trigger {
            get {
                return ResourceManager.GetString("Unit.Trigger", resourceCulture);
            }
        }
        
        public static string Unit_TrueFalse {
            get {
                return ResourceManager.GetString("Unit.TrueFalse", resourceCulture);
            }
        }
        
        public static string Unit_UpDown {
            get {
                return ResourceManager.GetString("Unit.UpDown", resourceCulture);
            }
        }
        
        public static string Unit_Voltage {
            get {
                return ResourceManager.GetString("Unit.Voltage", resourceCulture);
            }
        }
        
        public static string Unit_VolumeFlow {
            get {
                return ResourceManager.GetString("Unit.VolumeFlow", resourceCulture);
            }
        }
        
        public static string Unit_WindowDoor {
            get {
                return ResourceManager.GetString("Unit.WindowDoor", resourceCulture);
            }
        }
        
        public static string Unit_WindSpeed {
            get {
                return ResourceManager.GetString("Unit.WindSpeed", resourceCulture);
            }
        }
        
        public static string Unit_WindSpeedKmh {
            get {
                return ResourceManager.GetString("Unit.WindSpeedKmh", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Acknowledge {
            get {
                return ResourceManager.GetString("UnitEncoding.Acknowledge", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Active {
            get {
                return ResourceManager.GetString("UnitEncoding.Active", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Alarm {
            get {
                return ResourceManager.GetString("UnitEncoding.Alarm", resourceCulture);
            }
        }
        
        public static string UnitEncoding_And {
            get {
                return ResourceManager.GetString("UnitEncoding.And", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Calculated {
            get {
                return ResourceManager.GetString("UnitEncoding.Calculated", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Close {
            get {
                return ResourceManager.GetString("UnitEncoding.Close", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Cyclically {
            get {
                return ResourceManager.GetString("UnitEncoding.Cyclically", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Disable {
            get {
                return ResourceManager.GetString("UnitEncoding.Disable", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Down {
            get {
                return ResourceManager.GetString("UnitEncoding.Down", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Enable {
            get {
                return ResourceManager.GetString("UnitEncoding.Enable", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Fixed {
            get {
                return ResourceManager.GetString("UnitEncoding.Fixed", resourceCulture);
            }
        }
        
        public static string UnitEncoding_High {
            get {
                return ResourceManager.GetString("UnitEncoding.High", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Inactive {
            get {
                return ResourceManager.GetString("UnitEncoding.Inactive", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Increase {
            get {
                return ResourceManager.GetString("UnitEncoding.Increase", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Inverted {
            get {
                return ResourceManager.GetString("UnitEncoding.Inverted", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Low {
            get {
                return ResourceManager.GetString("UnitEncoding.Low", resourceCulture);
            }
        }
        
        public static string UnitEncoding_MoveUpDownAndStepMode {
            get {
                return ResourceManager.GetString("UnitEncoding.MoveUpDownAndStepMode", resourceCulture);
            }
        }
        
        public static string UnitEncoding_NoAction {
            get {
                return ResourceManager.GetString("UnitEncoding.NoAction", resourceCulture);
            }
        }
        
        public static string UnitEncoding_NoAlarm {
            get {
                return ResourceManager.GetString("UnitEncoding.NoAlarm", resourceCulture);
            }
        }
        
        public static string UnitEncoding_NoRamp {
            get {
                return ResourceManager.GetString("UnitEncoding.NoRamp", resourceCulture);
            }
        }
        
        public static string UnitEncoding_NotInverted {
            get {
                return ResourceManager.GetString("UnitEncoding.NotInverted", resourceCulture);
            }
        }
        
        public static string UnitEncoding_NotOccupied {
            get {
                return ResourceManager.GetString("UnitEncoding.NotOccupied", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Occupied {
            get {
                return ResourceManager.GetString("UnitEncoding.Occupied", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Off {
            get {
                return ResourceManager.GetString("UnitEncoding.Off", resourceCulture);
            }
        }
        
        public static string UnitEncoding_On {
            get {
                return ResourceManager.GetString("UnitEncoding.On", resourceCulture);
            }
        }
        
        public static string UnitEncoding_OnlyMoveUpDown {
            get {
                return ResourceManager.GetString("UnitEncoding.OnlyMoveUpDown", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Open {
            get {
                return ResourceManager.GetString("UnitEncoding.Open", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Or {
            get {
                return ResourceManager.GetString("UnitEncoding.Or", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Ramp {
            get {
                return ResourceManager.GetString("UnitEncoding.Ramp", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Reset {
            get {
                return ResourceManager.GetString("UnitEncoding.Reset", resourceCulture);
            }
        }
        
        public static string UnitEncoding_SceneA {
            get {
                return ResourceManager.GetString("UnitEncoding.SceneA", resourceCulture);
            }
        }
        
        public static string UnitEncoding_SceneB {
            get {
                return ResourceManager.GetString("UnitEncoding.SceneB", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Start {
            get {
                return ResourceManager.GetString("UnitEncoding.Start", resourceCulture);
            }
        }
        
        public static string UnitEncoding_StartStop {
            get {
                return ResourceManager.GetString("UnitEncoding.StartStop", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Stop {
            get {
                return ResourceManager.GetString("UnitEncoding.Stop", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Trigger {
            get {
                return ResourceManager.GetString("UnitEncoding.Trigger", resourceCulture);
            }
        }
        
        public static string UnitEncoding_True {
            get {
                return ResourceManager.GetString("UnitEncoding.True", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Up {
            get {
                return ResourceManager.GetString("UnitEncoding.Up", resourceCulture);
            }
        }
        
        public static string UnitEncoding_WindowClosed {
            get {
                return ResourceManager.GetString("UnitEncoding.WindowClosed", resourceCulture);
            }
        }
        
        public static string UnitEncoding_WindowOpen {
            get {
                return ResourceManager.GetString("UnitEncoding.WindowOpen", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Decrease {
            get {
                return ResourceManager.GetString("UnitEncoding.Decrease", resourceCulture);
            }
        }
        
        public static string UnitEncofing_False {
            get {
                return ResourceManager.GetString("UnitEncofing.False", resourceCulture);
            }
        }
        
        public static string UnknownDevice {
            get {
                return ResourceManager.GetString("UnknownDevice", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string Unit_Accelaration {
            get {
                return ResourceManager.GetString("Unit.Accelaration", resourceCulture);
            }
        }
        
        public static string Unit_AccelarationAngular {
            get {
                return ResourceManager.GetString("Unit.AccelarationAngular", resourceCulture);
            }
        }
        
        public static string Unit_ActivationEnergy {
            get {
                return ResourceManager.GetString("Unit.ActivationEnergy", resourceCulture);
            }
        }
        
        public static string Unit_Activity {
            get {
                return ResourceManager.GetString("Unit.Activity", resourceCulture);
            }
        }
        
        public static string Unit_AngleRad {
            get {
                return ResourceManager.GetString("Unit.AngleRad", resourceCulture);
            }
        }
        
        public static string Unit_AngularFrequency {
            get {
                return ResourceManager.GetString("Unit.AngularFrequency", resourceCulture);
            }
        }
        
        public static string Unit_AngularMomentum {
            get {
                return ResourceManager.GetString("Unit.AngularMomentum", resourceCulture);
            }
        }
        
        public static string Unit_AngularVelocity {
            get {
                return ResourceManager.GetString("Unit.AngularVelocity", resourceCulture);
            }
        }
        
        public static string Unit_Capacitance {
            get {
                return ResourceManager.GetString("Unit.Capacitance", resourceCulture);
            }
        }
        
        public static string Unit_ChargeDensitySurface {
            get {
                return ResourceManager.GetString("Unit.ChargeDensitySurface", resourceCulture);
            }
        }
        
        public static string Unit_ChargeDensityVolume {
            get {
                return ResourceManager.GetString("Unit.ChargeDensityVolume", resourceCulture);
            }
        }
        
        public static string Unit_Compressibillity {
            get {
                return ResourceManager.GetString("Unit.Compressibillity", resourceCulture);
            }
        }
        
        public static string Unit_Conductance {
            get {
                return ResourceManager.GetString("Unit.Conductance", resourceCulture);
            }
        }
        
        public static string Unit_CounterPulses {
            get {
                return ResourceManager.GetString("Unit.CounterPulses", resourceCulture);
            }
        }
        
        public static string Unit_CubicMeter {
            get {
                return ResourceManager.GetString("Unit.CubicMeter", resourceCulture);
            }
        }
        
        public static string Unit_Degrees {
            get {
                return ResourceManager.GetString("Unit.Degrees", resourceCulture);
            }
        }
        
        public static string Unit_Density {
            get {
                return ResourceManager.GetString("Unit.Density", resourceCulture);
            }
        }
        
        public static string Unit_ElectricalCharge {
            get {
                return ResourceManager.GetString("Unit.ElectricalCharge", resourceCulture);
            }
        }
        
        public static string Unit_ElectricalConductivity {
            get {
                return ResourceManager.GetString("Unit.ElectricalConductivity", resourceCulture);
            }
        }
        
        public static string Unit_ElectricalCurrent {
            get {
                return ResourceManager.GetString("Unit.ElectricalCurrent", resourceCulture);
            }
        }
        
        public static string Unit_ElectricalCurrentDensity {
            get {
                return ResourceManager.GetString("Unit.ElectricalCurrentDensity", resourceCulture);
            }
        }
        
        public static string Unit_ElectricDipoleMoment {
            get {
                return ResourceManager.GetString("Unit.ElectricDipoleMoment", resourceCulture);
            }
        }
        
        public static string Unit_ElectricFieldStrength {
            get {
                return ResourceManager.GetString("Unit.ElectricFieldStrength", resourceCulture);
            }
        }
        
        public static string Unit_ElectricFlux {
            get {
                return ResourceManager.GetString("Unit.ElectricFlux", resourceCulture);
            }
        }
        
        public static string Unit_ElectricFluxDensity {
            get {
                return ResourceManager.GetString("Unit.ElectricFluxDensity", resourceCulture);
            }
        }
        
        public static string Unit_ElectricPolarization {
            get {
                return ResourceManager.GetString("Unit.ElectricPolarization", resourceCulture);
            }
        }
        
        public static string Unit_ElectricPotential {
            get {
                return ResourceManager.GetString("Unit.ElectricPotential", resourceCulture);
            }
        }
        
        public static string Unit_ElectricPotentialDifference {
            get {
                return ResourceManager.GetString("Unit.ElectricPotentialDifference", resourceCulture);
            }
        }
        
        public static string Unit_ElectromagnetMoment {
            get {
                return ResourceManager.GetString("Unit.ElectromagnetMoment", resourceCulture);
            }
        }
        
        public static string Unit_ElectromotiveForce {
            get {
                return ResourceManager.GetString("Unit.ElectromotiveForce", resourceCulture);
            }
        }
        
        public static string Unit_Energy {
            get {
                return ResourceManager.GetString("Unit.Energy", resourceCulture);
            }
        }
        
        public static string Unit_Force {
            get {
                return ResourceManager.GetString("Unit.Force", resourceCulture);
            }
        }
        
        public static string Unit_Frequency {
            get {
                return ResourceManager.GetString("Unit.Frequency", resourceCulture);
            }
        }
        
        public static string Unit_HeatCapacity {
            get {
                return ResourceManager.GetString("Unit.HeatCapacity", resourceCulture);
            }
        }
        
        public static string Unit_HeatFlowRate {
            get {
                return ResourceManager.GetString("Unit.HeatFlowRate", resourceCulture);
            }
        }
        
        public static string Unit_HeatQuantity {
            get {
                return ResourceManager.GetString("Unit.HeatQuantity", resourceCulture);
            }
        }
        
        public static string Unit_Impendance {
            get {
                return ResourceManager.GetString("Unit.Impendance", resourceCulture);
            }
        }
        
        public static string Unit_Kelvin {
            get {
                return ResourceManager.GetString("Unit.Kelvin", resourceCulture);
            }
        }
        
        public static string Unit_Kilogram {
            get {
                return ResourceManager.GetString("Unit.Kilogram", resourceCulture);
            }
        }
        
        public static string Unit_kVAh {
            get {
                return ResourceManager.GetString("Unit.kVAh", resourceCulture);
            }
        }
        
        public static string Unit_kVARh {
            get {
                return ResourceManager.GetString("Unit.kVARh", resourceCulture);
            }
        }
        
        public static string Unit_kWh {
            get {
                return ResourceManager.GetString("Unit.kWh", resourceCulture);
            }
        }
        
        public static string Unit_LightQuantity {
            get {
                return ResourceManager.GetString("Unit.LightQuantity", resourceCulture);
            }
        }
        
        public static string Unit_Luminance {
            get {
                return ResourceManager.GetString("Unit.Luminance", resourceCulture);
            }
        }
        
        public static string Unit_LuminousFlux {
            get {
                return ResourceManager.GetString("Unit.LuminousFlux", resourceCulture);
            }
        }
        
        public static string Unit_LuminousIntensity {
            get {
                return ResourceManager.GetString("Unit.LuminousIntensity", resourceCulture);
            }
        }
        
        public static string Unit_MagneticFieldStrength {
            get {
                return ResourceManager.GetString("Unit.MagneticFieldStrength", resourceCulture);
            }
        }
        
        public static string Unit_MagneticFlux {
            get {
                return ResourceManager.GetString("Unit.MagneticFlux", resourceCulture);
            }
        }
        
        public static string Unit_MagneticFluxDensity {
            get {
                return ResourceManager.GetString("Unit.MagneticFluxDensity", resourceCulture);
            }
        }
        
        public static string Unit_MagneticMoment {
            get {
                return ResourceManager.GetString("Unit.MagneticMoment", resourceCulture);
            }
        }
        
        public static string Unit_MagneticPolarization {
            get {
                return ResourceManager.GetString("Unit.MagneticPolarization", resourceCulture);
            }
        }
        
        public static string Unit_Magnetization {
            get {
                return ResourceManager.GetString("Unit.Magnetization", resourceCulture);
            }
        }
        
        public static string Unit_MagnetomotiveForce {
            get {
                return ResourceManager.GetString("Unit.MagnetomotiveForce", resourceCulture);
            }
        }
        
        public static string Unit_MassFlux {
            get {
                return ResourceManager.GetString("Unit.MassFlux", resourceCulture);
            }
        }
        
        public static string Unit_Meter {
            get {
                return ResourceManager.GetString("Unit.Meter", resourceCulture);
            }
        }
        
        public static string Unit_Mol {
            get {
                return ResourceManager.GetString("Unit.Mol", resourceCulture);
            }
        }
        
        public static string Unit_Momentum {
            get {
                return ResourceManager.GetString("Unit.Momentum", resourceCulture);
            }
        }
        
        public static string Unit_PowerFactor {
            get {
                return ResourceManager.GetString("Unit.PowerFactor", resourceCulture);
            }
        }
        
        public static string Unit_Reactance {
            get {
                return ResourceManager.GetString("Unit.Reactance", resourceCulture);
            }
        }
        
        public static string Unit_Resistance {
            get {
                return ResourceManager.GetString("Unit.Resistance", resourceCulture);
            }
        }
        
        public static string Unit_Resistivity {
            get {
                return ResourceManager.GetString("Unit.Resistivity", resourceCulture);
            }
        }
        
        public static string Unit_Scene {
            get {
                return ResourceManager.GetString("Unit.Scene", resourceCulture);
            }
        }
        
        public static string Unit_SelfInductance {
            get {
                return ResourceManager.GetString("Unit.SelfInductance", resourceCulture);
            }
        }
        
        public static string Unit_SolidAngle {
            get {
                return ResourceManager.GetString("Unit.SolidAngle", resourceCulture);
            }
        }
        
        public static string Unit_SoundIntensity {
            get {
                return ResourceManager.GetString("Unit.SoundIntensity", resourceCulture);
            }
        }
        
        public static string Unit_Speed {
            get {
                return ResourceManager.GetString("Unit.Speed", resourceCulture);
            }
        }
        
        public static string Unit_SquareMeter {
            get {
                return ResourceManager.GetString("Unit.SquareMeter", resourceCulture);
            }
        }
        
        public static string Unit_Stress {
            get {
                return ResourceManager.GetString("Unit.Stress", resourceCulture);
            }
        }
        
        public static string Unit_SurfaceTension {
            get {
                return ResourceManager.GetString("Unit.SurfaceTension", resourceCulture);
            }
        }
        
        public static string Unit_TermalCapacity {
            get {
                return ResourceManager.GetString("Unit.TermalCapacity", resourceCulture);
            }
        }
        
        public static string Unit_TermalConductivity {
            get {
                return ResourceManager.GetString("Unit.TermalConductivity", resourceCulture);
            }
        }
        
        public static string Unit_ThermoelectricPower {
            get {
                return ResourceManager.GetString("Unit.ThermoelectricPower", resourceCulture);
            }
        }
        
        public static string Unit_Torque {
            get {
                return ResourceManager.GetString("Unit.Torque", resourceCulture);
            }
        }
        
        public static string Unit_VAh {
            get {
                return ResourceManager.GetString("Unit.VAh", resourceCulture);
            }
        }
        
        public static string Unit_VARh {
            get {
                return ResourceManager.GetString("Unit.VARh", resourceCulture);
            }
        }
        
        public static string Unit_VolumeFlux {
            get {
                return ResourceManager.GetString("Unit.VolumeFlux", resourceCulture);
            }
        }
        
        public static string Unit_Watt {
            get {
                return ResourceManager.GetString("Unit.Watt", resourceCulture);
            }
        }
        
        public static string Unit_Weight {
            get {
                return ResourceManager.GetString("Unit.Weight", resourceCulture);
            }
        }
        
        public static string Unit_Wh {
            get {
                return ResourceManager.GetString("Unit.Wh", resourceCulture);
            }
        }
        
        public static string Unit_Work {
            get {
                return ResourceManager.GetString("Unit.Work", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Hours {
            get {
                return ResourceManager.GetString("UnitEncoding.Hours", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Minutes {
            get {
                return ResourceManager.GetString("UnitEncoding.Minutes", resourceCulture);
            }
        }
        
        public static string UnitEncoding_Seconds {
            get {
                return ResourceManager.GetString("UnitEncoding.Seconds", resourceCulture);
            }
        }
        
        public static string Dpt4ByteCombinedInfoOnOff {
            get {
                return ResourceManager.GetString("Dpt4ByteCombinedInfoOnOff", resourceCulture);
            }
        }
        
        public static string DptAbsoluteTemperature {
            get {
                return ResourceManager.GetString("DptAbsoluteTemperature", resourceCulture);
            }
        }
        
        public static string DptAcceleration {
            get {
                return ResourceManager.GetString("DptAcceleration", resourceCulture);
            }
        }
        
        public static string DptAccelerationAngular {
            get {
                return ResourceManager.GetString("DptAccelerationAngular", resourceCulture);
            }
        }
        
        public static string DptAcknowledge {
            get {
                return ResourceManager.GetString("DptAcknowledge", resourceCulture);
            }
        }
        
        public static string DptActivationEnergy {
            get {
                return ResourceManager.GetString("DptActivationEnergy", resourceCulture);
            }
        }
        
        public static string DptActiveEnergy {
            get {
                return ResourceManager.GetString("DptActiveEnergy", resourceCulture);
            }
        }
        
        public static string DptActiveEnergy64 {
            get {
                return ResourceManager.GetString("DptActiveEnergy64", resourceCulture);
            }
        }
        
        public static string DptActiveEnergykWh {
            get {
                return ResourceManager.GetString("DptActiveEnergykWh", resourceCulture);
            }
        }
        
        public static string DptActivity {
            get {
                return ResourceManager.GetString("DptActivity", resourceCulture);
            }
        }
        
        public static string DptAirPressure {
            get {
                return ResourceManager.GetString("DptAirPressure", resourceCulture);
            }
        }
        
        public static string DptAirQuality {
            get {
                return ResourceManager.GetString("DptAirQuality", resourceCulture);
            }
        }
        
        public static string DptAlarm {
            get {
                return ResourceManager.GetString("DptAlarm", resourceCulture);
            }
        }
        
        public static string DptAlarmClassType {
            get {
                return ResourceManager.GetString("DptAlarmClassType", resourceCulture);
            }
        }
        
        public static string DptAlarmControl {
            get {
                return ResourceManager.GetString("DptAlarmControl", resourceCulture);
            }
        }
        
        public static string DptAlarmReaction {
            get {
                return ResourceManager.GetString("DptAlarmReaction", resourceCulture);
            }
        }
        
        public static string DptAmplitude {
            get {
                return ResourceManager.GetString("DptAmplitude", resourceCulture);
            }
        }
        
        public static string DptAngle {
            get {
                return ResourceManager.GetString("DptAngle", resourceCulture);
            }
        }
        
        public static string DptAngleDegree {
            get {
                return ResourceManager.GetString("DptAngleDegree", resourceCulture);
            }
        }
        
        public static string DptAngleRad {
            get {
                return ResourceManager.GetString("DptAngleRad", resourceCulture);
            }
        }
        
        public static string DptAngularFrequency {
            get {
                return ResourceManager.GetString("DptAngularFrequency", resourceCulture);
            }
        }
        
        public static string DptAngularMomentum {
            get {
                return ResourceManager.GetString("DptAngularMomentum", resourceCulture);
            }
        }
        
        public static string DptAngularVelocity {
            get {
                return ResourceManager.GetString("DptAngularVelocity", resourceCulture);
            }
        }
        
        public static string DptApparantEnergy {
            get {
                return ResourceManager.GetString("DptApparantEnergy", resourceCulture);
            }
        }
        
        public static string DptApparantEnergy64 {
            get {
                return ResourceManager.GetString("DptApparantEnergy64", resourceCulture);
            }
        }
        
        public static string DptApparantEnergykVAh {
            get {
                return ResourceManager.GetString("DptApparantEnergykVAh", resourceCulture);
            }
        }
        
        public static string DptArea {
            get {
                return ResourceManager.GetString("DptArea", resourceCulture);
            }
        }
        
        public static string DptBeafortWindForceScale {
            get {
                return ResourceManager.GetString("DptBeafortWindForceScale", resourceCulture);
            }
        }
        
        public static string DptBinaryValue {
            get {
                return ResourceManager.GetString("DptBinaryValue", resourceCulture);
            }
        }
        
        public static string DptBinaryValueControl {
            get {
                return ResourceManager.GetString("DptBinaryValueControl", resourceCulture);
            }
        }
        
        public static string DptBoolControl {
            get {
                return ResourceManager.GetString("DptBoolControl", resourceCulture);
            }
        }
        
        public static string DptBoolean {
            get {
                return ResourceManager.GetString("DptBoolean", resourceCulture);
            }
        }
        
        public static string DptBrightness {
            get {
                return ResourceManager.GetString("DptBrightness", resourceCulture);
            }
        }
        
        public static string DptBuildingMode {
            get {
                return ResourceManager.GetString("DptBuildingMode", resourceCulture);
            }
        }
        
        public static string DptCapacitance {
            get {
                return ResourceManager.GetString("DptCapacitance", resourceCulture);
            }
        }
        
        public static string DptCharackterAscii {
            get {
                return ResourceManager.GetString("DptCharackterAscii", resourceCulture);
            }
        }
        
        public static string DptCharackter_8859_1 {
            get {
                return ResourceManager.GetString("DptCharackter_8859_1", resourceCulture);
            }
        }
        
        public static string DptChargeDensitySurface {
            get {
                return ResourceManager.GetString("DptChargeDensitySurface", resourceCulture);
            }
        }
        
        public static string DptChargeDensityVolume {
            get {
                return ResourceManager.GetString("DptChargeDensityVolume", resourceCulture);
            }
        }
        
        public static string DptCommonTemperature {
            get {
                return ResourceManager.GetString("DptCommonTemperature", resourceCulture);
            }
        }
        
        public static string DptCompressibillity {
            get {
                return ResourceManager.GetString("DptCompressibillity", resourceCulture);
            }
        }
        
        public static string DptConductance {
            get {
                return ResourceManager.GetString("DptConductance", resourceCulture);
            }
        }
        
        public static string DptControlBlinds {
            get {
                return ResourceManager.GetString("DptControlBlinds", resourceCulture);
            }
        }
        
        public static string DptControlDimming {
            get {
                return ResourceManager.GetString("DptControlDimming", resourceCulture);
            }
        }
        
        public static string DptDate {
            get {
                return ResourceManager.GetString("DptDate", resourceCulture);
            }
        }
        
        public static string DptDateTime {
            get {
                return ResourceManager.GetString("DptDateTime", resourceCulture);
            }
        }
        
        public static string DptDecimalFactor {
            get {
                return ResourceManager.GetString("DptDecimalFactor", resourceCulture);
            }
        }
        
        public static string DptDeltaTimePeriod100Milliseconds {
            get {
                return ResourceManager.GetString("DptDeltaTimePeriod100Milliseconds", resourceCulture);
            }
        }
        
        public static string DptDeltaTimePeriod10Milliseconds {
            get {
                return ResourceManager.GetString("DptDeltaTimePeriod10Milliseconds", resourceCulture);
            }
        }
        
        public static string DptDeltaTimePeriodHours {
            get {
                return ResourceManager.GetString("DptDeltaTimePeriodHours", resourceCulture);
            }
        }
        
        public static string DptDeltaTimePeriodMilliseconds {
            get {
                return ResourceManager.GetString("DptDeltaTimePeriodMilliseconds", resourceCulture);
            }
        }
        
        public static string DptDeltaTimePeriodMinutes {
            get {
                return ResourceManager.GetString("DptDeltaTimePeriodMinutes", resourceCulture);
            }
        }
        
        public static string DptDeltaTimePeriodSeconds {
            get {
                return ResourceManager.GetString("DptDeltaTimePeriodSeconds", resourceCulture);
            }
        }
        
        public static string DptDensity {
            get {
                return ResourceManager.GetString("DptDensity", resourceCulture);
            }
        }
        
        public static string DptDeviceControl {
            get {
                return ResourceManager.GetString("DptDeviceControl", resourceCulture);
            }
        }
        
        public static string DptDimSendStyle {
            get {
                return ResourceManager.GetString("DptDimSendStyle", resourceCulture);
            }
        }
        
        public static string DptElectricalConductivity {
            get {
                return ResourceManager.GetString("DptElectricalConductivity", resourceCulture);
            }
        }
        
        public static string DptElectricalCurrent {
            get {
                return ResourceManager.GetString("DptElectricalCurrent", resourceCulture);
            }
        }
        
        public static string DptElectricCharge {
            get {
                return ResourceManager.GetString("DptElectricCharge", resourceCulture);
            }
        }
        
        public static string DptElectricCurrent {
            get {
                return ResourceManager.GetString("DptElectricCurrent", resourceCulture);
            }
        }
        
        public static string DptElectricCurrentDensity {
            get {
                return ResourceManager.GetString("DptElectricCurrentDensity", resourceCulture);
            }
        }
        
        public static string DptElectricDipoleMoment {
            get {
                return ResourceManager.GetString("DptElectricDipoleMoment", resourceCulture);
            }
        }
        
        public static string DptElectricDisplacement {
            get {
                return ResourceManager.GetString("DptElectricDisplacement", resourceCulture);
            }
        }
        
        public static string DptElectricFieldStrength {
            get {
                return ResourceManager.GetString("DptElectricFieldStrength", resourceCulture);
            }
        }
        
        public static string DptElectricFlux {
            get {
                return ResourceManager.GetString("DptElectricFlux", resourceCulture);
            }
        }
        
        public static string DptElectricFluxDensity {
            get {
                return ResourceManager.GetString("DptElectricFluxDensity", resourceCulture);
            }
        }
        
        public static string DptElectricPolarization {
            get {
                return ResourceManager.GetString("DptElectricPolarization", resourceCulture);
            }
        }
        
        public static string DptElectricPotential {
            get {
                return ResourceManager.GetString("DptElectricPotential", resourceCulture);
            }
        }
        
        public static string DptElectricPotentialDifference {
            get {
                return ResourceManager.GetString("DptElectricPotentialDifference", resourceCulture);
            }
        }
        
        public static string DptElectromagnetMoment {
            get {
                return ResourceManager.GetString("DptElectromagnetMoment", resourceCulture);
            }
        }
        
        public static string DptElectromotiveForce {
            get {
                return ResourceManager.GetString("DptElectromotiveForce", resourceCulture);
            }
        }
        
        public static string DptEnable {
            get {
                return ResourceManager.GetString("DptEnable", resourceCulture);
            }
        }
        
        public static string DptEnableControl {
            get {
                return ResourceManager.GetString("DptEnableControl", resourceCulture);
            }
        }
        
        public static string DptEnergy {
            get {
                return ResourceManager.GetString("DptEnergy", resourceCulture);
            }
        }
        
        public static string DptErrorClassHVAC {
            get {
                return ResourceManager.GetString("DptErrorClassHVAC", resourceCulture);
            }
        }
        
        public static string DptErrorClassSystem {
            get {
                return ResourceManager.GetString("DptErrorClassSystem", resourceCulture);
            }
        }
        
        public static string DptForce {
            get {
                return ResourceManager.GetString("DptForce", resourceCulture);
            }
        }
        
        public static string DptFrequency {
            get {
                return ResourceManager.GetString("DptFrequency", resourceCulture);
            }
        }
        
        public static string DptGeneralStatus {
            get {
                return ResourceManager.GetString("DptGeneralStatus", resourceCulture);
            }
        }
        
        public static string DptHeatCapacity {
            get {
                return ResourceManager.GetString("DptHeatCapacity", resourceCulture);
            }
        }
        
        public static string DptHeatFlowRate {
            get {
                return ResourceManager.GetString("DptHeatFlowRate", resourceCulture);
            }
        }
        
        public static string DptHeatQuantity {
            get {
                return ResourceManager.GetString("DptHeatQuantity", resourceCulture);
            }
        }
        
        public static string DptHumidity {
            get {
                return ResourceManager.GetString("DptHumidity", resourceCulture);
            }
        }
        
        public static string DptImpendance {
            get {
                return ResourceManager.GetString("DptImpendance", resourceCulture);
            }
        }
        
        public static string DptInputSource {
            get {
                return ResourceManager.GetString("DptInputSource", resourceCulture);
            }
        }
        
        public static string DptInvert {
            get {
                return ResourceManager.GetString("DptInvert", resourceCulture);
            }
        }
        
        public static string DptInvertedControl {
            get {
                return ResourceManager.GetString("DptInvertedControl", resourceCulture);
            }
        }
        
        public static string DptKelvinPerPercent {
            get {
                return ResourceManager.GetString("DptKelvinPerPercent", resourceCulture);
            }
        }
        
        public static string DptLength {
            get {
                return ResourceManager.GetString("DptLength", resourceCulture);
            }
        }
        
        public static string DptLengthInMillimeter {
            get {
                return ResourceManager.GetString("DptLengthInMillimeter", resourceCulture);
            }
        }
        
        public static string DptLightApplicationArea {
            get {
                return ResourceManager.GetString("DptLightApplicationArea", resourceCulture);
            }
        }
        
        public static string DptLightApplicationMode {
            get {
                return ResourceManager.GetString("DptLightApplicationMode", resourceCulture);
            }
        }
        
        public static string DptLightIntensity {
            get {
                return ResourceManager.GetString("DptLightIntensity", resourceCulture);
            }
        }
        
        public static string DptLightQuantity {
            get {
                return ResourceManager.GetString("DptLightQuantity", resourceCulture);
            }
        }
        
        public static string DptLogicalFunction {
            get {
                return ResourceManager.GetString("DptLogicalFunction", resourceCulture);
            }
        }
        
        public static string DptLongDeltaTimeSec {
            get {
                return ResourceManager.GetString("DptLongDeltaTimeSec", resourceCulture);
            }
        }
        
        public static string DptLuminance {
            get {
                return ResourceManager.GetString("DptLuminance", resourceCulture);
            }
        }
        
        public static string DptLuminousFlux {
            get {
                return ResourceManager.GetString("DptLuminousFlux", resourceCulture);
            }
        }
        
        public static string DptLuminousIntensity {
            get {
                return ResourceManager.GetString("DptLuminousIntensity", resourceCulture);
            }
        }
        
        public static string DptMagneticFieldStrength {
            get {
                return ResourceManager.GetString("DptMagneticFieldStrength", resourceCulture);
            }
        }
        
        public static string DptMagneticFlux {
            get {
                return ResourceManager.GetString("DptMagneticFlux", resourceCulture);
            }
        }
        
        public static string DptMagneticFluxDensity {
            get {
                return ResourceManager.GetString("DptMagneticFluxDensity", resourceCulture);
            }
        }
        
        public static string DptMagneticMoment {
            get {
                return ResourceManager.GetString("DptMagneticMoment", resourceCulture);
            }
        }
        
        public static string DptMagneticPolarization {
            get {
                return ResourceManager.GetString("DptMagneticPolarization", resourceCulture);
            }
        }
        
        public static string DptMagnetization {
            get {
                return ResourceManager.GetString("DptMagnetization", resourceCulture);
            }
        }
        
        public static string DptMagnetomotiveForce {
            get {
                return ResourceManager.GetString("DptMagnetomotiveForce", resourceCulture);
            }
        }
        
        public static string DptMass {
            get {
                return ResourceManager.GetString("DptMass", resourceCulture);
            }
        }
        
        public static string DptMassFlux {
            get {
                return ResourceManager.GetString("DptMassFlux", resourceCulture);
            }
        }
        
        public static string DptMol {
            get {
                return ResourceManager.GetString("DptMol", resourceCulture);
            }
        }
        
        public static string DptMomentum {
            get {
                return ResourceManager.GetString("DptMomentum", resourceCulture);
            }
        }
        
        public static string DptOccMode {
            get {
                return ResourceManager.GetString("DptOccMode", resourceCulture);
            }
        }
        
        public static string DptOccupancy {
            get {
                return ResourceManager.GetString("DptOccupancy", resourceCulture);
            }
        }
        
        public static string DptOnOffAction {
            get {
                return ResourceManager.GetString("DptOnOffAction", resourceCulture);
            }
        }
        
        public static string DptOpenClose {
            get {
                return ResourceManager.GetString("DptOpenClose", resourceCulture);
            }
        }
        
        public static string DptOpenCloseControl {
            get {
                return ResourceManager.GetString("DptOpenCloseControl", resourceCulture);
            }
        }
        
        public static string DptPercentU8 {
            get {
                return ResourceManager.GetString("DptPercentU8", resourceCulture);
            }
        }
        
        public static string DptPercentV16 {
            get {
                return ResourceManager.GetString("DptPercentV16", resourceCulture);
            }
        }
        
        public static string DptPercentV8 {
            get {
                return ResourceManager.GetString("DptPercentV8", resourceCulture);
            }
        }
        
        public static string DptPhaseAngleDeg {
            get {
                return ResourceManager.GetString("DptPhaseAngleDeg", resourceCulture);
            }
        }
        
        public static string DptPhaseAngleRad {
            get {
                return ResourceManager.GetString("DptPhaseAngleRad", resourceCulture);
            }
        }
        
        public static string DptPower {
            get {
                return ResourceManager.GetString("DptPower", resourceCulture);
            }
        }
        
        public static string DptPower1 {
            get {
                return ResourceManager.GetString("DptPower1", resourceCulture);
            }
        }
        
        public static string DptPowerDensity {
            get {
                return ResourceManager.GetString("DptPowerDensity", resourceCulture);
            }
        }
        
        public static string DptPowerFactor {
            get {
                return ResourceManager.GetString("DptPowerFactor", resourceCulture);
            }
        }
        
        public static string DptPressure {
            get {
                return ResourceManager.GetString("DptPressure", resourceCulture);
            }
        }
        
        public static string DptPriority {
            get {
                return ResourceManager.GetString("DptPriority", resourceCulture);
            }
        }
        
        public static string DptPropDataType {
            get {
                return ResourceManager.GetString("DptPropDataType", resourceCulture);
            }
        }
        
        public static string DptPSUMode {
            get {
                return ResourceManager.GetString("DptPSUMode", resourceCulture);
            }
        }
        
        public static string DptRainAmount {
            get {
                return ResourceManager.GetString("DptRainAmount", resourceCulture);
            }
        }
        
        public static string DptRamp {
            get {
                return ResourceManager.GetString("DptRamp", resourceCulture);
            }
        }
        
        public static string DptRampControl {
            get {
                return ResourceManager.GetString("DptRampControl", resourceCulture);
            }
        }
        
        public static string DptReactance {
            get {
                return ResourceManager.GetString("DptReactance", resourceCulture);
            }
        }
        
        public static string DptReactiveEnergy {
            get {
                return ResourceManager.GetString("DptReactiveEnergy", resourceCulture);
            }
        }
        
        public static string DptReactiveEnergy64 {
            get {
                return ResourceManager.GetString("DptReactiveEnergy64", resourceCulture);
            }
        }
        
        public static string DptReactiveEnergykVARh {
            get {
                return ResourceManager.GetString("DptReactiveEnergykVARh", resourceCulture);
            }
        }
        
        public static string DptReset {
            get {
                return ResourceManager.GetString("DptReset", resourceCulture);
            }
        }
        
        public static string DptResistance {
            get {
                return ResourceManager.GetString("DptResistance", resourceCulture);
            }
        }
        
        public static string DptResistivity {
            get {
                return ResourceManager.GetString("DptResistivity", resourceCulture);
            }
        }
        
        public static string DptRotationAngle {
            get {
                return ResourceManager.GetString("DptRotationAngle", resourceCulture);
            }
        }
        
        public static string DptScaling {
            get {
                return ResourceManager.GetString("DptScaling", resourceCulture);
            }
        }
        
        public static string DptScene {
            get {
                return ResourceManager.GetString("DptScene", resourceCulture);
            }
        }
        
        public static string DptSceneAB {
            get {
                return ResourceManager.GetString("DptSceneAB", resourceCulture);
            }
        }
        
        public static string DptSceneControl {
            get {
                return ResourceManager.GetString("DptSceneControl", resourceCulture);
            }
        }
        
        public static string DptSCLOMode {
            get {
                return ResourceManager.GetString("DptSCLOMode", resourceCulture);
            }
        }
        
        public static string DptSelfInductance {
            get {
                return ResourceManager.GetString("DptSelfInductance", resourceCulture);
            }
        }
        
        public static string DptSensorSelect {
            get {
                return ResourceManager.GetString("DptSensorSelect", resourceCulture);
            }
        }
        
        public static string DptShutterBlindsMode {
            get {
                return ResourceManager.GetString("DptShutterBlindsMode", resourceCulture);
            }
        }
        
        public static string DptSolidAngle {
            get {
                return ResourceManager.GetString("DptSolidAngle", resourceCulture);
            }
        }
        
        public static string DptSoundIntensity {
            get {
                return ResourceManager.GetString("DptSoundIntensity", resourceCulture);
            }
        }
        
        public static string DptSpeed {
            get {
                return ResourceManager.GetString("DptSpeed", resourceCulture);
            }
        }
        
        public static string DptStartStop {
            get {
                return ResourceManager.GetString("DptStartStop", resourceCulture);
            }
        }
        
        public static string DptStartStopControl {
            get {
                return ResourceManager.GetString("DptStartStopControl", resourceCulture);
            }
        }
        
        public static string DptState {
            get {
                return ResourceManager.GetString("DptState", resourceCulture);
            }
        }
        
        public static string DptStateControl {
            get {
                return ResourceManager.GetString("DptStateControl", resourceCulture);
            }
        }
        
        public static string DptStatusWithMode3 {
            get {
                return ResourceManager.GetString("DptStatusWithMode3", resourceCulture);
            }
        }
        
        public static string DptStep {
            get {
                return ResourceManager.GetString("DptStep", resourceCulture);
            }
        }
        
        public static string DptStepControl {
            get {
                return ResourceManager.GetString("DptStepControl", resourceCulture);
            }
        }
        
        public static string DptStress {
            get {
                return ResourceManager.GetString("DptStress", resourceCulture);
            }
        }
        
        public static string DptStringAscii {
            get {
                return ResourceManager.GetString("DptStringAscii", resourceCulture);
            }
        }
        
        public static string DptString_8859_1 {
            get {
                return ResourceManager.GetString("DptString_8859_1", resourceCulture);
            }
        }
        
        public static string DptSurfaceTension {
            get {
                return ResourceManager.GetString("DptSurfaceTension", resourceCulture);
            }
        }
        
        public static string DptSwitch {
            get {
                return ResourceManager.GetString("DptSwitch", resourceCulture);
            }
        }
        
        public static string DptSwitchControl {
            get {
                return ResourceManager.GetString("DptSwitchControl", resourceCulture);
            }
        }
        
        public static string DptTariff {
            get {
                return ResourceManager.GetString("DptTariff", resourceCulture);
            }
        }
        
        public static string DptTemperature {
            get {
                return ResourceManager.GetString("DptTemperature", resourceCulture);
            }
        }
        
        public static string DptTemperatureDifference {
            get {
                return ResourceManager.GetString("DptTemperatureDifference", resourceCulture);
            }
        }
        
        public static string DptTemperatureDifference1 {
            get {
                return ResourceManager.GetString("DptTemperatureDifference1", resourceCulture);
            }
        }
        
        public static string DptTemperatureF {
            get {
                return ResourceManager.GetString("DptTemperatureF", resourceCulture);
            }
        }
        
        public static string DptTemperatureGradient {
            get {
                return ResourceManager.GetString("DptTemperatureGradient", resourceCulture);
            }
        }
        
        public static string DptTermalCapacity {
            get {
                return ResourceManager.GetString("DptTermalCapacity", resourceCulture);
            }
        }
        
        public static string DptTermalConductivity {
            get {
                return ResourceManager.GetString("DptTermalConductivity", resourceCulture);
            }
        }
        
        public static string DptThermoelectricPower {
            get {
                return ResourceManager.GetString("DptThermoelectricPower", resourceCulture);
            }
        }
        
        public static string DptTime {
            get {
                return ResourceManager.GetString("DptTime", resourceCulture);
            }
        }
        
        public static string DptTimeDelay {
            get {
                return ResourceManager.GetString("DptTimeDelay", resourceCulture);
            }
        }
        
        public static string DptTimeDifference {
            get {
                return ResourceManager.GetString("DptTimeDifference", resourceCulture);
            }
        }
        
        public static string DptTimePeriod100Milliseconds {
            get {
                return ResourceManager.GetString("DptTimePeriod100Milliseconds", resourceCulture);
            }
        }
        
        public static string DptTimePeriod10Milliseconds {
            get {
                return ResourceManager.GetString("DptTimePeriod10Milliseconds", resourceCulture);
            }
        }
        
        public static string DptTimePeriodHours {
            get {
                return ResourceManager.GetString("DptTimePeriodHours", resourceCulture);
            }
        }
        
        public static string DptTimePeriodMilliseconds {
            get {
                return ResourceManager.GetString("DptTimePeriodMilliseconds", resourceCulture);
            }
        }
        
        public static string DptTimePeriodMinutes {
            get {
                return ResourceManager.GetString("DptTimePeriodMinutes", resourceCulture);
            }
        }
        
        public static string DptTimePeriodSeconds {
            get {
                return ResourceManager.GetString("DptTimePeriodSeconds", resourceCulture);
            }
        }
        
        public static string DptTorque {
            get {
                return ResourceManager.GetString("DptTorque", resourceCulture);
            }
        }
        
        public static string DptTrigger {
            get {
                return ResourceManager.GetString("DptTrigger", resourceCulture);
            }
        }
        
        public static string DptUEICurrentmA {
            get {
                return ResourceManager.GetString("DptUEICurrentmA", resourceCulture);
            }
        }
        
        public static string DptUpDown {
            get {
                return ResourceManager.GetString("DptUpDown", resourceCulture);
            }
        }
        
        public static string DptUpDownAction {
            get {
                return ResourceManager.GetString("DptUpDownAction", resourceCulture);
            }
        }
        
        public static string DptUpDownControl {
            get {
                return ResourceManager.GetString("DptUpDownControl", resourceCulture);
            }
        }
        
        public static string DptValue1Count {
            get {
                return ResourceManager.GetString("DptValue1Count", resourceCulture);
            }
        }
        
        public static string DptValue1UCount {
            get {
                return ResourceManager.GetString("DptValue1UCount", resourceCulture);
            }
        }
        
        public static string DptValue2Count {
            get {
                return ResourceManager.GetString("DptValue2Count", resourceCulture);
            }
        }
        
        public static string DptValue2UCount {
            get {
                return ResourceManager.GetString("DptValue2UCount", resourceCulture);
            }
        }
        
        public static string DptValue4Count {
            get {
                return ResourceManager.GetString("DptValue4Count", resourceCulture);
            }
        }
        
        public static string DptValue4UCount {
            get {
                return ResourceManager.GetString("DptValue4UCount", resourceCulture);
            }
        }
        
        public static string DptVariableString_8859_1 {
            get {
                return ResourceManager.GetString("DptVariableString_8859_1", resourceCulture);
            }
        }
        
        public static string DptVariableString_UTF8 {
            get {
                return ResourceManager.GetString("DptVariableString_UTF8", resourceCulture);
            }
        }
        
        public static string DptVoltage {
            get {
                return ResourceManager.GetString("DptVoltage", resourceCulture);
            }
        }
        
        public static string DptVolume {
            get {
                return ResourceManager.GetString("DptVolume", resourceCulture);
            }
        }
        
        public static string DptVolumeFlow {
            get {
                return ResourceManager.GetString("DptVolumeFlow", resourceCulture);
            }
        }
        
        public static string DptVolumeFlux {
            get {
                return ResourceManager.GetString("DptVolumeFlux", resourceCulture);
            }
        }
        
        public static string DptWeight {
            get {
                return ResourceManager.GetString("DptWeight", resourceCulture);
            }
        }
        
        public static string DptWindowDoor {
            get {
                return ResourceManager.GetString("DptWindowDoor", resourceCulture);
            }
        }
        
        public static string DptWindSpeed {
            get {
                return ResourceManager.GetString("DptWindSpeed", resourceCulture);
            }
        }
        
        public static string DptWindSpeedKmh {
            get {
                return ResourceManager.GetString("DptWindSpeedKmh", resourceCulture);
            }
        }
        
        public static string DptWork {
            get {
                return ResourceManager.GetString("DptWork", resourceCulture);
            }
        }
        
        public static string Enum_NothingSelected {
            get {
                return ResourceManager.GetString("Enum_NothingSelected", resourceCulture);
            }
        }
    }
}
